server:
  port: 7777

logging:
  level:
    org:
      springframework:
        boot: INFOÃ³
    pl:
      futurecollars:
        invoicing: INFO
        invoicing.db: DEBUG

spring:
  profiles:
    active: mongo
  flyway:
    enabled: false
